# AICP Internship Task Week 1

<b>Write a NumPy program to create an array of all even integers from 30 to 70.<b>

In [15]:
#importing numpy
import numpy as np

In [16]:
a=np.arange(30,70,2,dtype='int64')
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68], dtype=int64)

<b>Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.<b>

In [17]:
from numpy import random

x=random.normal(loc=0,size=15)
x

array([ 0.88807309, -0.28165152, -0.36688271,  0.09286981, -1.20229585,
        2.80672516, -1.42145594,  0.78394047,  1.38696204,  0.06821779,
        0.90592652,  0.86174238, -1.95947622,  0.88731493,  0.81937125])

<b>How to compute the cross-product of two matrices in NumPy?
<b>

In [18]:
X=np.array([[1,2],[5,6]])
Y=np.array([[4,6],[3,8]])
crossprod=np.cross(X,Y)
crossprod

array([-2, 22])

<b>How to compute the determinant of an array using NumPy?<b>

In [19]:
X=np.array([[4,2],[3,4]])
det=np.linalg.det(X)
det

10.000000000000002

<b>How to create a 3x3x3 array with random values using NumPy?<b>


In [24]:
from numpy import random
x=np.random.random((3,3,3))
x

array([[[0.6394714 , 0.47798214, 0.10826845],
        [0.04703727, 0.93726588, 0.68790573],
        [0.7555901 , 0.08604928, 0.11399684]],

       [[0.2110846 , 0.13429768, 0.79550861],
        [0.66234788, 0.52937281, 0.34890339],
        [0.39555119, 0.52692261, 0.8123175 ]],

       [[0.29677246, 0.0424613 , 0.39699825],
        [0.14437729, 0.16134866, 0.56416051],
        [0.92719162, 0.78752819, 0.37788637]]])

<b>How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?<b>

In [29]:
a=np.random.random((5,5))
print(a)
max=a.max()
min=a.min()
print("\nmax=")
print(max)
print("\nmin=")
print(min)

[[0.73532137 0.76459821 0.71035801 0.39208685 0.85533109]
 [0.52258749 0.25699535 0.17020579 0.14254029 0.98002808]
 [0.8722731  0.80132485 0.95035289 0.64953151 0.9620263 ]
 [0.6477219  0.43384038 0.21404599 0.21633736 0.01111635]
 [0.94009282 0.70419178 0.83076541 0.5783477  0.59422784]]

max=
0.9800280798361712

min=
0.011116354648785576


<b>How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?<b>

In [35]:
x=np.array([[3,4,4],[7,4,6]])
mean=x.mean(dtype="int64")
print("mean=")
print(mean)
std=x.std(dtype="int64")
print("standard deviation=")
print(std)
var=x.var(dtype="int64")
print("variance=")
print(var)

mean=
4
standard deviation=
1
variance=
2
